name: Send LINE Notification for Garbage Day

on:
  schedule:
    # 日本時間の毎日18時 (UTCの毎日9時) に実行
    - cron: '0 9 * * *'
  workflow_dispatch: # 手動実行も可能にする

jobs:
  notify:
    runs-on: ubuntu-latest
    env:
      LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
      LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
      TZ: 'Asia/Tokyo' # タイムゾーンを日本時間に設定
      USER_TOWN_NAME: '和田多中町（上記以外の地域）'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 適切なPythonバージョンを指定

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run notification script
      run: python garbage_notice.py